### ISSUE TITLE
Any plan to support io.js?

### ISSUE THREAD

**Issue by imskull** [hokein/node-minizip#1]
Got lots of errors when I updated `nan` to 2.0.5 and compiled:

```
../src/zip_async_worker.h:14:31: error: unknown class name 'NanAsyncWorker'; did you mean 'ZipAsyncWorker'?
class ZipAsyncWorker : public NanAsyncWorker {
                              ^~~~~~~~~~~~~~
                              ZipAsyncWorker
../src/zip_async_worker.h:14:7: note: 'ZipAsyncWorker' declared here
class ZipAsyncWorker : public NanAsyncWorker {
      ^
../src/zip_async_worker.h:14:31: error: base class has incomplete type
class ZipAsyncWorker : public NanAsyncWorker {
                       ~~~~~~~^~~~~~~~~~~~~~
../src/zip_async_worker.h:14:7: note: definition of 'zip::ZipAsyncWorker' is not complete until the closing '}'
class ZipAsyncWorker : public NanAsyncWorker {
```

**Comment by imskull** [comment]
Nevemind, I get it compiled succeed now, but don't why it crashes at the latest NW.js. will send a PR if I can fix it.
